# Generated by Django 3.2 on 2022-07-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterrecepients',
            name='name',
        ),
    ]
