# Generated by Django 3.2 on 2022-07-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_newsletterrecepients_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterRecepients',
            new_name='SubscribedUsers',
        ),
    ]
