# Generated by Django 3.2 on 2022-07-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='app.spaces'),
        ),
    ]
