# Generated by Django 3.2 on 2022-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_newsletterrecepients_subscribedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
