# Generated by Django 3.2 on 2022-07-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsers',
        ),
    ]
